name: study_flutter
version: 1.0.2+1
homepage: https://pub.dev/
repository: https://pub.dev/
environment: 
  sdk: '>=2.17.0'
dependencies: 
  connectivity_plus: ^4.0.2
  dartx: ^1.2.0
  dio: ^5.3.3
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^8.0.0
  flutter_localizations: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  freezed: ^2.4.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  pretty_logger: ^1.0.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.11
 
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
 
flutter: 
  assets: 
    - assets/images/
    - assets/icon/
    - assets/abi/
  
  uses-material-design: true
flutter_intl: 
  enabled: true
