name: study_flutter
version: 1.0.2+1
homepage: https://pub.dev/
repository: https://pub.dev/
environment: 
  sdk: '>=2.17.0'
dependencies: 
  analyzer: ^5.2.0
  adaptive_dialog: ^1.9.0+2
  connectivity_plus: ^4.0.1
  convert: ^3.1.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  dart_ipify: ^1.1.1
  dartx: ^1.1.0
  device_info_plus: ^9.0.2
  dio: ^5.3.3
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  event_bus: ^2.0.0
  expandable: ^5.0.1
  expandable_page_view: ^1.0.17
  file_picker: ^5.2.4
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^15.1.0+1
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.6.0
  flutter_share: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  freezed: ^2.2.1
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  google_fonts: ^6.0.0
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.1
  injectable: ^2.0.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  just_audio: ^0.9.31
  keyboard_dismisser: ^3.0.0
  lint: ^2.1.2
  local_auth: ^2.1.2
  logger: ^2.0.2
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  queue: ^3.1.0+2
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  web3dart: ^2.7.1
  image_res: ^0.3.0
  flutter_form_builder: ^9.1.0
  flutter_expandable_widget: ^1.0.5

  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  
dev_dependencies: 
  auto_route_generator: any
  build_runner: ^2.4.6
  injectable_generator: ^2.0.1
  intl_utils: ^2.8.4
  json_serializable: ^6.5.4
  pubspec_dependency_sorter: ^1.0.3
  retrofit_generator: any
  
  flutter_test: 
    sdk: flutter
  objectbox_generator: any
flutter: 
  assets: 
    - assets/images/
    - assets/icon/
    - assets/abi/
  
  uses-material-design: true
flutter_intl: 
  enabled: true
